import type { ParseMetadata } from './types';

/**
 * Matches Cura (`;LAYER:n`), PrusaSlicer/Slic3r (`;LAYER_CHANGE`), and the
 * Rhino/GH exporter's `;Layer n` (space-separated) markers. The digit
 * requirement keeps `;Layer height: 0.2` from counting as a layer change.
 */
export function isLayerChangeComment(comment: string): boolean {
  return /^LAYER[:\s]\s*\d+/i.test(comment) || /^LAYER_CHANGE/i.test(comment);
}

// Cura and PrusaSlicer both tag feature/region blocks with a `;TYPE:` comment
// (e.g. "TYPE:WALL-OUTER", "TYPE:Perimeter", "TYPE:FILL").
const FEATURE_TYPE_RE = /^TYPE:\s*(.+)/i;

/** Returns the feature/type tag from a `;TYPE:` comment, or null if this isn't one. */
export function parseFeatureTypeComment(comment: string): string | null {
  const match = comment.match(FEATURE_TYPE_RE);
  return match ? match[1].trim() : null;
}

// "generated by PrusaSlicer ..." / "Generated with Python / GH" (custom scripts use "with")
const GENERATED_BY_RE = /generated (?:by|with)\s+(.+)/i;
// PrusaSlicer/Slic3r: "; estimated printing time (normal mode) = 1h 2m 3s"
const PRUSA_TIME_RE = /estimated printing time.*?=\s*(.+)/i;
const PRUSA_FILAMENT_MM_RE = /filament used \[mm\]\s*=\s*([\d.]+)/i;
const PRUSA_FILAMENT_G_RE = /filament used \[g\]\s*=\s*([\d.]+)/i;
// Cura: ";TIME:12345" (seconds), ";Filament used: 2.5m" (meters)
const CURA_TIME_RE = /^TIME:\s*(\d+)/i;
const CURA_FILAMENT_M_RE = /^Filament used:\s*([\d.]+)\s*m\b/i;
// Cura: ";Layer height: 0.2"; PrusaSlicer/Slic3r: "; layer_height = 0.2"
const CURA_LAYER_HEIGHT_RE = /^Layer height:\s*([\d.]+)/i;
const PRUSA_LAYER_HEIGHT_RE = /^layer_height\s*=\s*([\d.]+)/i;
// PrusaSlicer/Slic3r: "; nozzle_diameter = 0.4,0.4,0.4,0.4" (one per extruder, take the first)
const PRUSA_NOZZLE_DIAMETER_RE = /^nozzle_diameter\s*=\s*([\d.]+)/i;
// Cura/Ultimaker: ";NOZZLE_DIAMETER:2.0"
const CURA_NOZZLE_DIAMETER_RE = /^NOZZLE_DIAMETER:\s*([\d.]+)/i;
// PrusaSlicer/Slic3r: "; filament_type = PLA"
const PRUSA_FILAMENT_TYPE_RE = /^filament_type\s*=\s*(\S+)/i;
// Cura: ";TARGET_MACHINE.NAME:Ultimaker S5"; PrusaSlicer/Slic3r: "; printer_model = MK3S"
const CURA_MACHINE_RE = /^TARGET_MACHINE\.NAME:\s*(.+)/i;
const PRUSA_PRINTER_MODEL_RE = /^printer_model\s*=\s*(.+)/i;
// Cura/Ultimaker split across two comment lines: ";File created 20260703" then "; at 6:46:58 PM"
const CURA_FILE_CREATED_RE = /^File created\s+(.+)/i;
const CURA_CREATED_TIME_RE = /^at\s+(.+)/i;
// Custom header schema for script-generated (Rhino/GH) files — see docs/exporter-header.md.
// ";Machine: RISE E3D gantry", ";Material: Concrete", ";Created: 2026-06-05 14:02:11"
const CUSTOM_MACHINE_RE = /^Machine:\s*(.+)/i;
// Requires a letter in the value so Ultimaker's numeric ";MATERIAL:1" (a
// material index, not a name) doesn't show up as "Material: 1".
const CUSTOM_MATERIAL_RE = /^Material:\s*([^\s].*[A-Za-z].*|[A-Za-z])$/i;
const CUSTOM_CREATED_RE = /^Created:\s*(.+)/i;
// ";Bead width: 40" / ";Extrusion width: 40" — large-scale analogue of nozzle diameter.
const CUSTOM_BEAD_WIDTH_RE = /^(?:Bead|Extrusion) width:\s*([\d.]+)/i;
// ";Build volume: 1200 x 600 x 600" (mm) and ";Origin: center" / ";Origin: corner"
const CUSTOM_BUILD_VOLUME_RE = /^Build volume:\s*([\d.]+)\s*[x×]\s*([\d.]+)\s*[x×]\s*([\d.]+)/i;
const CUSTOM_ORIGIN_RE = /^Origin:\s*(center|corner)/i;

/**
 * Best-effort extraction of header/footer stats from comment lines. Every
 * field is optional — a file with none of these still renders fine.
 */
export function collectMetadata(commentLines: string[]): ParseMetadata {
  const metadata: ParseMetadata = { raw: commentLines };
  // "File created <date>" and its time are two separate, adjacent comment lines.
  let pendingCreatedDate: string | undefined;

  for (const line of commentLines) {
    if (metadata.createdAt === undefined) {
      if (pendingCreatedDate !== undefined) {
        const createdTime = line.match(CURA_CREATED_TIME_RE);
        if (createdTime) metadata.createdAt = `${pendingCreatedDate} ${createdTime[1].trim()}`;
        pendingCreatedDate = undefined;
      } else {
        const fileCreated = line.match(CURA_FILE_CREATED_RE);
        if (fileCreated) {
          pendingCreatedDate = fileCreated[1].trim();
        } else {
          const created = line.match(CUSTOM_CREATED_RE);
          if (created) metadata.createdAt = created[1].trim();
        }
      }
    }

    if (metadata.material === undefined) {
      const material = line.match(CUSTOM_MATERIAL_RE);
      if (material) metadata.material = material[1].trim();
    }

    if (metadata.buildVolume === undefined) {
      const volume = line.match(CUSTOM_BUILD_VOLUME_RE);
      if (volume) {
        metadata.buildVolume = {
          x: parseFloat(volume[1]),
          y: parseFloat(volume[2]),
          z: parseFloat(volume[3]),
        };
      }
    }

    if (metadata.originMode === undefined) {
      const origin = line.match(CUSTOM_ORIGIN_RE);
      if (origin) metadata.originMode = origin[1].toLowerCase() as 'center' | 'corner';
    }

    if (!metadata.slicer) {
      const generatedBy = line.match(GENERATED_BY_RE);
      if (generatedBy) metadata.slicer = generatedBy[1].trim();
    }

    if (metadata.printTimeSeconds === undefined) {
      const prusaTime = line.match(PRUSA_TIME_RE);
      if (prusaTime) {
        metadata.printTimeSeconds = parseDurationToSeconds(prusaTime[1]);
      } else {
        const curaTime = line.match(CURA_TIME_RE);
        if (curaTime) metadata.printTimeSeconds = parseInt(curaTime[1], 10);
      }
    }

    if (metadata.filamentUsedMm === undefined) {
      const prusaMm = line.match(PRUSA_FILAMENT_MM_RE);
      if (prusaMm) {
        metadata.filamentUsedMm = parseFloat(prusaMm[1]);
      } else {
        const curaM = line.match(CURA_FILAMENT_M_RE);
        if (curaM) metadata.filamentUsedMm = parseFloat(curaM[1]) * 1000;
      }
    }

    if (metadata.filamentUsedGrams === undefined) {
      const prusaG = line.match(PRUSA_FILAMENT_G_RE);
      if (prusaG) metadata.filamentUsedGrams = parseFloat(prusaG[1]);
    }

    if (metadata.layerHeightMm === undefined) {
      const curaHeight = line.match(CURA_LAYER_HEIGHT_RE);
      if (curaHeight) {
        metadata.layerHeightMm = parseFloat(curaHeight[1]);
      } else {
        const prusaHeight = line.match(PRUSA_LAYER_HEIGHT_RE);
        if (prusaHeight) metadata.layerHeightMm = parseFloat(prusaHeight[1]);
      }
    }

    if (metadata.nozzleDiameterMm === undefined) {
      const prusaNozzle = line.match(PRUSA_NOZZLE_DIAMETER_RE);
      const curaNozzle = prusaNozzle ? null : line.match(CURA_NOZZLE_DIAMETER_RE);
      const beadWidth = prusaNozzle || curaNozzle ? null : line.match(CUSTOM_BEAD_WIDTH_RE);
      const match = prusaNozzle ?? curaNozzle ?? beadWidth;
      if (match) metadata.nozzleDiameterMm = parseFloat(match[1]);
    }

    if (metadata.filamentType === undefined) {
      const filamentType = line.match(PRUSA_FILAMENT_TYPE_RE);
      if (filamentType) metadata.filamentType = filamentType[1];
    }

    if (metadata.machineName === undefined) {
      const curaMachine = line.match(CURA_MACHINE_RE);
      const prusaModel = curaMachine ? null : line.match(PRUSA_PRINTER_MODEL_RE);
      const customMachine = curaMachine || prusaModel ? null : line.match(CUSTOM_MACHINE_RE);
      const match = curaMachine ?? prusaModel ?? customMachine;
      if (match) metadata.machineName = match[1].trim();
    }
  }

  return metadata;
}

function parseDurationToSeconds(text: string): number | undefined {
  const re = /(\d+)\s*(h|m|s)/gi;
  let total = 0;
  let matched = false;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) !== null) {
    matched = true;
    const value = parseInt(match[1], 10);
    const unit = match[2].toLowerCase();
    if (unit === 'h') total += value * 3600;
    else if (unit === 'm') total += value * 60;
    else total += value;
  }
  return matched ? total : undefined;
}
