import type { ParseMetadata } from './types';

/** Matches both Cura (`;LAYER:n`) and PrusaSlicer/Slic3r (`;LAYER_CHANGE`) markers. */
export function isLayerChangeComment(comment: string): boolean {
  return /^LAYER:\d+/i.test(comment) || /^LAYER_CHANGE/i.test(comment);
}

// Cura and PrusaSlicer both tag feature/region blocks with a `;TYPE:` comment
// (e.g. "TYPE:WALL-OUTER", "TYPE:Perimeter", "TYPE:FILL").
const FEATURE_TYPE_RE = /^TYPE:\s*(.+)/i;

/** Returns the feature/type tag from a `;TYPE:` comment, or null if this isn't one. */
export function parseFeatureTypeComment(comment: string): string | null {
  const match = comment.match(FEATURE_TYPE_RE);
  return match ? match[1].trim() : null;
}

const GENERATED_BY_RE = /generated by\s+(.+)/i;
// PrusaSlicer/Slic3r: "; estimated printing time (normal mode) = 1h 2m 3s"
const PRUSA_TIME_RE = /estimated printing time.*?=\s*(.+)/i;
const PRUSA_FILAMENT_MM_RE = /filament used \[mm\]\s*=\s*([\d.]+)/i;
const PRUSA_FILAMENT_G_RE = /filament used \[g\]\s*=\s*([\d.]+)/i;
// Cura: ";TIME:12345" (seconds), ";Filament used: 2.5m" (meters)
const CURA_TIME_RE = /^TIME:\s*(\d+)/i;
const CURA_FILAMENT_M_RE = /^Filament used:\s*([\d.]+)\s*m\b/i;
// Cura: ";Layer height: 0.2"; PrusaSlicer/Slic3r: "; layer_height = 0.2"
const CURA_LAYER_HEIGHT_RE = /^Layer height:\s*([\d.]+)/i;
const PRUSA_LAYER_HEIGHT_RE = /^layer_height\s*=\s*([\d.]+)/i;
// PrusaSlicer/Slic3r: "; nozzle_diameter = 0.4,0.4,0.4,0.4" (one per extruder, take the first)
const PRUSA_NOZZLE_DIAMETER_RE = /^nozzle_diameter\s*=\s*([\d.]+)/i;
// PrusaSlicer/Slic3r: "; filament_type = PLA"
const PRUSA_FILAMENT_TYPE_RE = /^filament_type\s*=\s*(\S+)/i;

/**
 * Best-effort extraction of header/footer stats from comment lines. Every
 * field is optional — a file with none of these still renders fine.
 */
export function collectMetadata(commentLines: string[]): ParseMetadata {
  const metadata: ParseMetadata = { raw: commentLines };

  for (const line of commentLines) {
    if (!metadata.slicer) {
      const generatedBy = line.match(GENERATED_BY_RE);
      if (generatedBy) metadata.slicer = generatedBy[1].trim();
    }

    if (metadata.printTimeSeconds === undefined) {
      const prusaTime = line.match(PRUSA_TIME_RE);
      if (prusaTime) {
        metadata.printTimeSeconds = parseDurationToSeconds(prusaTime[1]);
      } else {
        const curaTime = line.match(CURA_TIME_RE);
        if (curaTime) metadata.printTimeSeconds = parseInt(curaTime[1], 10);
      }
    }

    if (metadata.filamentUsedMm === undefined) {
      const prusaMm = line.match(PRUSA_FILAMENT_MM_RE);
      if (prusaMm) {
        metadata.filamentUsedMm = parseFloat(prusaMm[1]);
      } else {
        const curaM = line.match(CURA_FILAMENT_M_RE);
        if (curaM) metadata.filamentUsedMm = parseFloat(curaM[1]) * 1000;
      }
    }

    if (metadata.filamentUsedGrams === undefined) {
      const prusaG = line.match(PRUSA_FILAMENT_G_RE);
      if (prusaG) metadata.filamentUsedGrams = parseFloat(prusaG[1]);
    }

    if (metadata.layerHeightMm === undefined) {
      const curaHeight = line.match(CURA_LAYER_HEIGHT_RE);
      if (curaHeight) {
        metadata.layerHeightMm = parseFloat(curaHeight[1]);
      } else {
        const prusaHeight = line.match(PRUSA_LAYER_HEIGHT_RE);
        if (prusaHeight) metadata.layerHeightMm = parseFloat(prusaHeight[1]);
      }
    }

    if (metadata.nozzleDiameterMm === undefined) {
      const nozzleDiameter = line.match(PRUSA_NOZZLE_DIAMETER_RE);
      if (nozzleDiameter) metadata.nozzleDiameterMm = parseFloat(nozzleDiameter[1]);
    }

    if (metadata.filamentType === undefined) {
      const filamentType = line.match(PRUSA_FILAMENT_TYPE_RE);
      if (filamentType) metadata.filamentType = filamentType[1];
    }
  }

  return metadata;
}

function parseDurationToSeconds(text: string): number | undefined {
  const re = /(\d+)\s*(h|m|s)/gi;
  let total = 0;
  let matched = false;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) !== null) {
    matched = true;
    const value = parseInt(match[1], 10);
    const unit = match[2].toLowerCase();
    if (unit === 'h') total += value * 3600;
    else if (unit === 'm') total += value * 60;
    else total += value;
  }
  return matched ? total : undefined;
}
